### ISSUE TITLE
Exception if angle ist 90 and data-font is I2OF5TXT

### ISSUE THREAD

**Issue by GoogleCodeExporter** [innoventsolutions/birt-controls-lib#10]
```
What steps will reproduce the problem?
1. Query data to get a text-field with font I2OF5TXT
2. and angle is 90 or -90 or 89

What is the expected output? What do you see instead?
a rotated barcode "Text" with angle 90

What happens: an exception:
Caused by: java.lang.IllegalArgumentException: im == null!
   at javax.imageio.ImageIO.write(ImageIO.java:1457)
   at blackboard.birt.extensions.rotatedtext.RotatedTextPresentationImpl.onRowSets(RotatedTextPresentationImpl.java:76)

What version of the product are you using? On what operating system?
- Birt eclipse 2.6.1
- controls lib 2.5.2.1
- Mac OS X 10.6.8

this problem happend wenn i want to rotate text with font I2OF5TXT and with 
angle 90 or -90 or 89 or 270. It doesn't happend with angle 88 or other, but 
the barcode with 88 is tooo smal. 

thanks for any help


```

Original issue reported on code.google.com by `nafar...@gmx.de` on 8 Jul 2011 at 11:34

**Comment by SteveSchafer-Innovent** [comment]
In BIRT 4.5.0, there is no error on Linux but on Windows I get java.lang.IllegalArgumentException: Width (0) and height (126) cannot be <= 0

**Comment by SteveSchafer-Innovent** [comment]
On Windows, java.awt.FontMetrics.getStringBounds() returns height = 0 for that font.  When at a multiple of 90 degrees it produces an illegal image (with a width or height of zero).  At another angle it results in the image being partly cropped because the offset is wrong.

**Comment by SteveSchafer-Innovent** [comment]
It is beyond the current scope to fix this, so closing for now.
